// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6lLPfPh3sklGX9nggRAlQ6Qwb6RAHgO0',
    appId: '1:663940182485:web:17bf0eba5132abd7ff8d5c',
    messagingSenderId: '663940182485',
    projectId: 'smart-app-33082',
    authDomain: 'smart-app-33082.firebaseapp.com',
    storageBucket: 'smart-app-33082.firebasestorage.app',
    measurementId: 'G-JK387B60H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDriEHwpuay_korbuaws_iJDTCNZwN2uA0',
    appId: '1:663940182485:android:4fb75a50f173da16ff8d5c',
    messagingSenderId: '663940182485',
    projectId: 'smart-app-33082',
    storageBucket: 'smart-app-33082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY7jj8fx3kT-DyM9Xvx5KweYag0NdBPtY',
    appId: '1:663940182485:ios:1eb4d89f5ea8ddaaff8d5c',
    messagingSenderId: '663940182485',
    projectId: 'smart-app-33082',
    storageBucket: 'smart-app-33082.firebasestorage.app',
    iosClientId: '663940182485-t3ts4s9makel0q4fgapjh2rgnqsn050h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY7jj8fx3kT-DyM9Xvx5KweYag0NdBPtY',
    appId: '1:663940182485:ios:1eb4d89f5ea8ddaaff8d5c',
    messagingSenderId: '663940182485',
    projectId: 'smart-app-33082',
    storageBucket: 'smart-app-33082.firebasestorage.app',
    iosClientId: '663940182485-t3ts4s9makel0q4fgapjh2rgnqsn050h.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6lLPfPh3sklGX9nggRAlQ6Qwb6RAHgO0',
    appId: '1:663940182485:web:44a45195223a373fff8d5c',
    messagingSenderId: '663940182485',
    projectId: 'smart-app-33082',
    authDomain: 'smart-app-33082.firebaseapp.com',
    storageBucket: 'smart-app-33082.firebasestorage.app',
    measurementId: 'G-LSVHHS42JV',
  );
}
